baseURL = "https://www.imdavidwang.com/"
languageCode = "zh-CN"
title = "My Blog"
theme = "PaperMod"
[pagination]
  pagerSize = 12

[params]
  env = "production"
  description = "My personal blog"
  author = "bluestone"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowFullTextinRSS = true
  mainSections = ["notes"]

[params.homeInfoParams]
  Title = "Hi there"
  Content = "Welcome to my blog"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/bluestonemds"

[menu]
  [[menu.main]]
    identifier = "notes"
    name = "笔记"
    url = "/notes/"
    weight = 10
  [[menu.main]]
    identifier = "photos"
    name = "照片"
    url = "/photos/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
