baseURL = "https://www.imdavidwang.com/"
locale = "zh-CN"
title = "我的博客"
theme = "PaperMod"
defaultContentLanguage = "zh"
[pagination]
  pagerSize = 12

[params]
  env = "production"
  description = "我的个人博客"
  author = "bluestone"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowFullTextinRSS = true
  mainSections = ["notes"]

[menu]
  [[menu.main]]
    identifier = "notes"
    name = "笔记"
    url = "/notes/"
    weight = 10
  [[menu.main]]
    identifier = "photos"
    name = "照片"
    url = "/photos/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 30
